# frontend/Dockerfile
FROM node:20 AS builder
WORKDIR /app
COPY . .
RUN npm install

RUN npm run build
RUN ls -l /app/dist
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
