# Dockerfile.worker

FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY . .

RUN go build -o worker_node worker_node.go

# Imagen final minimalista
FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/worker_node .

CMD ["./worker_node"]
