version: "3.8"

services:
  main_node:
    build:
      context: .
      dockerfile: Dockerfile.main
    ports:
      - "8080:8080"   # API REST
      - "8000:8000"   # Comunicación TCP con workers
    volumes:
      - ./data:/app/data
    depends_on:
      - mongo
      - redis

  worker_node_1:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - main_node

  worker_node_2:
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - main_node

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - main_node

volumes:
  mongo_data:
